### ISSUE TITLE
Mods not working after the update 1.5.4

### ISSUE THREAD

**Issue by JohnnySounds** [Kizari/Flagrum#103]
Ever since the update non of the mods work anymore, Iv tried reinstalling the game even and nothig....am I the only one?

**Comment by Rinual** [comment]
Please review the template for new issues as to prevent vague and impossible to help posts such as this. 

![image](https://github.com/Kizari/Flagrum/assets/108095289/a9d51b57-1b19-467e-ac60-7e13b51e4d0a)

**Comment by Kizari** [comment]
Closing this as no further information has been provided, so there's nothing to be actioned.
