### ISSUE TITLE
Custom Materials for .binmods inconsistently display in game

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#11]
After creating a new material preset for emissive textures using the following material and code:

```
const string templateName = "NAMED_HUMAN_OUTFIT_E";
const string sourceEarcPath = @$"C:\...\...\...\FINAL FANTASY XV\datas\character\nh\nh00\entry\nh00_base.earc";
const string sourceMaterialPath = "data://character/nh/nh00/model_022/materials/nh00_022_basic_01_mat.gmtl";

using var unpacker = new Unpacker(sourceEarcPath);
var sourceBytes = unpacker.UnpackFileByQuery(sourceMaterialPath, out _);
var sourceMaterial = new MaterialReader(sourceBytes).Read();

var outJson = JsonConvert.SerializeObject(sourceMaterial);
File.WriteAllText(@$"G:\FFXV\MaterialTesting\{templateName}.json", outJson);

MaterialToPython.ConvertFromJsonFile(@$"G:\FFXV\MaterialTesting\{templateName}.json",
@$"C:\whatever\output\folder\{templateName}.py");
```
The outfit usually displays correctly as intended. However, since re-creating 1 of 5 of the outfits with the new material with an emissive texture. The old emissive material is utilizing NH Glass. The game will produce one of the following results:

1) Game loads both outfits fine
2) The four old emissive materials are invisible (other parts of outfits not using emissive textures load fine) New outfit loads in fine
3) The new material is invisible (other parts of outfits not using emissive textures load fine) Old outfits load in fine

I have yet to see an instance of all outfits failing to load emissive textures. It is either one, the other, or neither having issues. 

<hr>

Worth exploring further by user:
1) New material was added after NAMED_HUMAN_OUTFIT in the middle of the list as opposed to at the end of the list.
-(ignored as the material displays correctly in Plugin and usually works as intended in game)

2) Disabling the mod with the new material did not fix the issue with the emissive outfits not loading consistently. However, deleting the mod entirely seemed to. (Requires further verification to say with high degree of confidence)

**Comment by Kizari** [comment]
This issue may become redundant after the custom materials project, but it will be worth keeping in mind for two reasons.
1. The issue may present on said custom materials
2. The issue may become a problem if we add more presets to Flagrum in future

This information will be vital for understanding these issues when they arise.

**Comment by Kizari** [comment]
Closing this, as while it may be useful as a reference for future, it is not an active issue anymore and can be referenced from the closed issues if/when needed.
