### ISSUE TITLE
the mod does not start

### ISSUE THREAD

**Issue by erickds15** [Kizari/Flagrum#110]
I followed the installation guide here on github, and everything happens normally without a warning or anything, I installed some mods, namely 'quick boot, unlock character guest and the community texture patch' and it also didn't give an error warning nor anything to install.

However, when I open the game the mods simply don't start, it doesn't quick boot and the guest character doesn't appear.

However, when I went to manually install another mod 'rebalanced ascension', the mod worked normally.

Is there any method for me to resolve this?

Or if not, would you be able to install the other mods manually?

![ff15 location](https://github.com/Kizari/Flagrum/assets/96899060/89d94834-3019-4702-9f82-ed489b01f653)

ps: translated by Google translate it was bad in English...

**Comment by Kizari** [comment]
Hi there. This problem occurs if Flagrum is used with the wrong executable. The mod loader only works with the latest official ffxv_s.exe from Steam. I'm unsure if the executable from other stores such as Origin are the same or not. This means that older versions of the game will not work with the mod loader, and other executables such as the Avatara mod or unofficial builds won't work either.

**Comment by erickds15** [comment]
I bought it from the Xbox store so it shouldn't work on the platform...

**Comment by Kizari** [comment]
While sadly not a fix, the mod loader update in 1.5.17 will now inform the user if the game version they are running is incompatible with Flagrum to avoid this sort of confusion in future.
