### ISSUE TITLE
Mods aren't working

### ISSUE THREAD

**Issue by devilfish666** [Kizari/Flagrum#115]
I have the Steam version of the game (episode Ardyn DLC bought and installed later if that matters.) After installing mods through Flagrum as well as the Steam Workshop, the mods installed with Flagrum aren't taking effect in the game. The Workshop mods take effect just fine.

Flagrum has the correct .exe and binmod.list paths in settings. I've verified the game files through Steam, tried regenerating the file index and doing a force reset/cleanup. It's very likely something to do with my setup because the same modlist works just fine on my other PC.

**Comment by Kizari** [comment]
I''m afraid I have no idea what's wrong there based on this information alone. The only case I know of where mods don't work at all is if the executable isn't the latest authentic Steam version of the game for Windows, but by the sounds of it, you have that one—especially considering it works on your other PC fine. Is there anything atypical about your FFXV install or your PC setup that may help understand why it may be failing on that one?

**Comment by devilfish666** [comment]
Sorry for the lack of info, I'm completely stumped as well, I can't see a reason why it wouldn't work. It's definitely the latest, fully updated Steam version. The install folder isn't the default path (it's C:\Games\Steam\steamapps\common\FINAL FANTASY XV\ffxv_s.exe) but it's not using the default path either on my other PC. I tried turning off as many background processes as possible to see if any of them are interfering but no luck. 

One thing I noticed is that only the workshop mod I have is listed in the binmod.list file but I'm not sure if Flagrum-installed mods are supposed to be listed there at all. 

Since the problem doesn't appear to be with Flagrum at all I'll try and work it out and report here if I ever do find out what's wrong, but I thought it couldn't hurt to ask.

**Comment by Kizari** [comment]
Non-default install path shouldn't be an issue at all as you observed. Binmod.list should only list Steam Workshop mods, so that's definitely not it. It's very strange. Don't suppose that PC is on a different OS to your other one? I wonder if maybe there's a different exe for Windows 7 or something that Steam chooses automatically when installing the game?

**Comment by devilfish666** [comment]
The old PC is Windows 10 Home and this one is Windows 11 Pro. I tried grabbing the old .exe and running it with the new install just to try it but that didn't do anything.

The only odd thing I noticed is that generating a new file index went very fast (maybe three seconds) compared to the previous install. And on first install of Flagrum I got the message about indexing files, which stayed there for a very long time, but only until I clicked to another tab in Flagrum.

**Comment by Kizari** [comment]
Huh, it didn't work on the new system even with the same .exe that works on the old system? Now that's peculiar. I haven't "upgraded" to Windows 11 yet, so no idea if it's possibly related to that in some way. Have you tried clicking the "Force Reset/Cleanup" button in Settings and then enabling the mods again to see if that helps at all?

**Comment by devilfish666** [comment]
Yes, I copied just the .exe from my old Windows 10 system to the new Windows 11 system and ran it with just one Flagrum mod installed (I'm testing it with the Quick Boot mod to see if it's working right away) and it made no difference.

I've tried the Force Cleanup/Reset option. I also did a clean install (redownloaded the game through Steam, no Nexus/Workshop mods, just Flagrum with that one mod) and the problem persists.

**Comment by devilfish666** [comment]
Just tried it and no dice. I'll try "downgrading" to Windows 10 when I have the time just to see if that's it, but it's clearly something hyperspecific to my setup and not the program's fault. I'll try downgrading to Windows 10 when I have the time just to see if that's it but I'll just play without mods. (Unless there's another way to install fmods?) I really appreciate your time!

**Comment by Kizari** [comment]
Sadly there isn't any other way to install FMODs. It's a format that was designed specifically to only hold the minimum amount of information needed to reconstruct mods to reduce file sizes, avoid copyright infringement by not reuploading other parts of existing archives, and to reduce conflicts between mods by allowing multiple mods to target the same archive.

Unfortunately a consequence of this is that Flagrum needs to use the data from the FMOD on the client PC to produce the final mod, which is what is ultimately applied to the game.

**However**, you can try [the method](https://github.com/Kizari/Flagrum/issues/118#issuecomment-1846169012) that Linux users with Windows PCs use to get the mods on their Linux machines or Steam Decks if you aren't able to figure out what it is about your other setup that doesn't agree with Flagrum.

**Comment by kaioken32** [comment]
> I have the Steam version of the game (episode Ardyn DLC bought and installed later if that matters.) After installing mods through Flagrum as well as the Steam Workshop, the mods installed with Flagrum aren't taking effect in the game. The Workshop mods take effect just fine.
> 
> Flagrum has the correct .exe and binmod.list paths in settings. I've verified the game files through Steam, tried regenerating the file index and doing a force reset/cleanup. It's very likely something to do with my setup because the same modlist works just fine on my other PC.

mod works for version 1.4.10
if you have the old file, install that and don;t let it update to latest

**Comment by Kizari** [comment]
Closing this as there hasn't been any further information in over a month. Hoping things went well for you. Feel free to reopen the issue if you have anything further to add in future.

**Comment by Kizari** [comment]
The mod loader has been reworked in Flagrum 1.5.17 in an attempt to address this issue. If it still isn't working, please leave a comment on #174 with as much detail as possible.
