### ISSUE TITLE
Multiple issues when expected files are missing from an EARC mod

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#12]
Flagrum's Error window, or at least the one that pertains to warning the user about missing files, loses all useful messages for the user about the error if the list of files is longer than the predefined box size. 

![image](https://user-images.githubusercontent.com/108095289/189418888-1e93fe31-52fd-4ba9-b30f-e508d13e5082.png)

Developer has recommended the following fix:

- Change the modal type it uses so it's using an auto-size modal with scrollbars for overflow

**Comment by Rinual** [comment]
Developer could also consider adding an equivalent error message for instances where user simply enables a mod with missing files. 

Enabling a mod with inaccessible (either missing or renamed) results in Flagrum silently crashing with the following log. 
[crash.txt](https://github.com/Kizari/Flagrum/files/9538593/crash.txt)

Note: The crash log does correctly change for encrypted drives that were not unlocked, correctly identifying that issue as well.

**Comment by Kizari** [comment]
These issues have been fixed with Flagrum 1.3.
