### ISSUE TITLE
Game Crashes When Multiple Mods Target Specific Bins

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#130]
Title: Game Crashes When Multiple Mods Target Specific Bins

**Describe the bug**
When multiple game mods target specific bins, such as vehicles.bin, residentcharacter.bin, and weapons.bin, the game crashes under certain conditions. This occurs even with unmodified bin files, suggesting that the issue lies within the mod loading process rather than the bins themselves. It appears potentially related to having multiple sources targeting the parent `common/autobuild.earc` file containing the bins triggers the crash.

[modpack.zip](https://github.com/Kizari/Flagrum/files/14199534/modpack.zip) (unzip for .fmod file, do not legacy install)

**To Reproduce**
1. Install and activate the "vanilla bin crash 1" mod targeting vehicles.bin.
2. Install and activate the "vanilla bin crash 2" mod targeting residentcharacter.bin and weapons.bin.
3. Launch the game.
4. Observe the crash.

**Expected behavior**
The game should load without crashing, even with multiple mods targeting the specified bins.

**Additional context**
The issue can be further observed by comparing the behavior with the AIO (All-In-One) mod option, which merges all three bins into a single mod. The attached .fmod file contains the necessary files for testing and reproducing the issue.

**note**
Sometimes the game crashes upon booting, sometimes when loading a saved game, and on at least one occasion, it fully booted but exhibited noticeable unexpected behavior. These variations in crash occurrence highlight the sporadic nature of the issue and its potential impact on different game states.

**Comment by Kizari** [comment]
What's really interesting about this is that the all-in-one version works. That *should* be functionally identical to having the three as separate mods, but clearly isn't the case. I can only then assume there's a bug with the mod builder. Perhaps it's adding multiple references when it should only have one or something. I'll need to try the reproduction case and see what the difference is once the mods are applied to the game.

**Comment by Rinual** [comment]
Yeah, that distinction is how it went unnoticed for me, as I had merged my edits to those bins to produce compatibility versions of mods that target both.

**Comment by Kizari** [comment]
Fixed in 1.5.10.
