### ISSUE TITLE
Indexing game files message sometimes persists after indexing is finished

### ISSUE THREAD

**Issue by Kizari** [Kizari/Flagrum#131]
**Describe the bug**
As per title.

**To Reproduce**
Unable to reliably reproduce.

**Expected behavior**
The message should automatically clear when indexing is finished.

**Additional context**
Can be worked around by simply changing tab on the left menu to get rid of it. It's a poor user experience though so should ideally fix this if possible.

**Comment by Rinual** [comment]
Note: This issue has persisted for nearly 2 years 
![image](https://github.com/Kizari/Flagrum/assets/108095289/ae679b93-6c4a-4035-999a-81e15cbef32e)

Can probably be ignored unless it drives you particularly nuts.

**Comment by Kizari** [comment]
It used to drive me quite nuts since I'd be answering questions about it every other day. Not so much anymore though. It's pretty minor, but wouldn't hurt to resolve if it's not too tricky when I have a bit of down time and nothing else I feel like doing.

**Comment by Kizari** [comment]
Fixed in 1.5.12.

**Comment by Rinual** [comment]
Had someone have this yesterday… 😅
