### ISSUE TITLE
Setup.exe won't open

### ISSUE THREAD

**Issue by Spaghettislut** [Kizari/Flagrum#133]
First time installing. Setup.exe will not run no matter what I do
tried adding it as an exception in my antivirus, turning off my firewall, running as admin but so far nothing's worked.

**Comment by Kizari** [comment]
Can't say that's one I've come across before. Have run the latest Setup.exe on my end just to double-check and it's still okay.

What operating system are you using?

Is the Flagrum folder getting created in `%LOCALAPPDATA%\Flagrum`?
If so, are there any crash logs present there?

The only other thing I could think to attempt would be to disable the antivirus completely briefly to see if it will run. I've heard of some of the more aggressive ones still causing problems even with exceptions added.

**Comment by Spaghettislut** [comment]
I'm running windows 11 home version 10.0.22631

There's no folder in AppData Local, the .exe doesn't seem to do anything at all.

I already tried disabling windows defender. I might just reinstall windows and see if that works.

**Comment by Kizari** [comment]
I'm really sorry, I have no idea what would cause this. Have had many users install Flagrum fine on Windows 11. Without any logs in local app data, it's impossible to diagnose what's going wrong there.

Could you try run Setup.exe from the commandline to output a log? Best way to do this is:
- Press Windows+R
- Type "cmd" and hit enter, a command prompt should appear
- Type `cd C:\path\to\folder\with\setup` and hit enter. Make sure to use the actual location of the folder containing Setup.exe
- Type `Setup.exe --log output.txt` and hit enter

After doing this, a file called "output.txt" should appear in the folder next to Setup.exe. If you can attach that file, it may provide some clues as to what's going wrong.

**Comment by Kizari** [comment]
Closing this as there is not enough information to action anything.
