### ISSUE TITLE
Creating a new preset, refuses to remember the selected model

### ISSUE THREAD

**Issue by zhenniguan** [Kizari/Flagrum#138]
**Describe the bug**
Adding a new model to the model replacement preset just vanishes after selecting the model.
Same issue happens if you attempt to write manually

**To reproduce**
1) Workshop mod tab in Flagrum
2) New mod --> model replacement --> create preset
3) Browse and select any random model
4) The blanket remains empty despite clearly selecting a model
5) Manually typing automatically deletes it

**Expected behavior:**
That the newly selected model in the preset will stay instead of vanishing^^''

It's a newly installed Flagrum version v. 1.5.11

Picture below is  the same issue but with a duplicated preset instead
![image](https://github.com/Kizari/Flagrum/assets/160407345/ea529867-7f4c-4d0e-85fe-c5bc1799eb30)

**Comment by Kizari** [comment]
Thank you for your report. I am able to reproduce the issue following your instructions. I will fix this in the next update.
