### ISSUE TITLE
Mods don't work

### ISSUE THREAD

**Issue by M3gan3Sama** [Kizari/Flagrum#142]
Is this app work with caracked version of the games (fitgrils)?
i useed this app and install some mods but none of them worked

**Comment by Kizari** [comment]
Great question! I'm glad to hear that you're interested in Flagrum and have used it to install some mods. Unfortunately Flagrum only supports the latest legitimate Steam version of the game at this time. I would consider extending support to other legitimate versions from other game stores if they have different executables, but I'm not currently aware of any that are used. For legal and ethical reasons, there are no plans to ever support illegitimate copies of the game. I appreciate your understanding.

**Comment by M3gan3Sama** [comment]
so i have another question, can i turn .fmods to items (.ffxvbinmod)?
