### ISSUE TITLE
Cant seem interact with a specific .gfxbin or material in game 

### ISSUE THREAD

**Issue by canplx** [Kizari/Flagrum#143]
I was told from the discord that  `data://effects/resource/resource/mdl/_temp/nk_warp_tgs_02.gmdl`  and  `data://effects/resource/resource/mdl/_temp/luminyshader1.gmtl`   these were the warp decoy that Noctis has. But editing them seems to have no change on it.  

I have also found a similar name `data://effects/battle/warp_tgs_01sw.vfx` but editing this also doesn't seem to have an effect

**Comment by canplx** [comment]
I have also found that a similar name at `data://effects/battle/warp_tgs_01sw.vfx`  but editing this also doesn't seem to have an effect

**Comment by canplx** [comment]
I should also mention I haven't tried anything xml related

**Comment by Kizari** [comment]
Apologies, been really busy with work the last couple of weeks. Glad to hear you got it sorted. What was the solution? May help in future if the same or similar issue comes up again, or if something with the user experience needs to be tweaked if it was something to do with Flagrum that needed to be manually worked around.

**Comment by canplx** [comment]
That's all right, It turns out it was another file than I was told. I believe the file I was swapping was for a different purpose in the game. Or it just was not able to be edited.

**Comment by Kizari** [comment]
Ahh I see, that'll do it! Thanks for reporting back, much appreciated.
