### ISSUE TITLE
Flagrum won't open

### ISSUE THREAD

**Issue by GlitchLokison** [Kizari/Flagrum#145]
So yesterday I tried to open Flagrum cus I wanted to play Final Fantasy XV on Windows, and wanted to check my mods; however, it said the version I had was no longer supported and asked me to update, so I hit the update button, but half way through it said there was an error and shut down the program, so I tried opening it again after restarting my computer to try and get the update back, that didn't work because the program wouldn't open, so I uninstalled it and reinstalled, but still no luck. Flagrum won't open at all and I dunno what to do. I'm running Windows 11.

**Comment by Rinual** [comment]
did you try deleting this folder? `C:\Users\Rinual\AppData\Local\Flagrum` with the name adjusted for your pc?

**Comment by Rinual** [comment]
Let us know if the issue persists after doing the above

**Comment by Kizari** [comment]
Closing this as no further information was provided.

**Comment by GlitchLokison** [comment]
sorry was in the middle of moving, so had no internet. I removed the file and reinstalled, but it still won't open. Am I doing something wrong?
