### ISSUE TITLE
[NotReallyABugOrMaybeJustASmallOne]: Flagrum has no respect for the game I'm modding

### ISSUE THREAD

**Issue by Lennn888** [Kizari/Flagrum#151]
### Operating System

Windows 11 64-Bit

### Game Version

Latest Steam Release

### Version

1.5.12

### Description of the bug

Flagrum keeps calling the game FFXV even though it's not!!! Happens at least when I save a mod while game is running. Will update if I find more of these disrespectful comments.

### Steps to reproduce the bug

1. Open Forspoken
2. Open Flagrum and try to save a mod
3. :sadface: because even Flagrum has no respect for this game

### Screenshots

![disrespect](https://github.com/Kizari/Flagrum/assets/3669773/7dbcd7a7-a8b1-455d-a02d-ddabed9771d0)

### Code of Conduct

- [X] I confirm that I have ensured this bug hasn't already been reported in another issue on this repository.
- [X] I confirm that this bug report is pertaining to Flagrum, not an individual mod, the game itself, or an issue with my system or files.
- [X] I confirm that I am using a legitimate copy of the game.
- [X] I confirm that I installed Flagrum with a clean installation of the game, and have not used any tools other than Flagrum to mod my game files.
- [X] If my issue relates to the game itself crashing or exhibiting unexpected behaviour, I confirm that I have tried running a clean unmodded installation of the game to see if this resolves my issue before filing a bug report.

**Comment by Kizari** [comment]
LOL, an unfathomable atrocity indeed! The audacity is beyond comprehension. How will I ever rise from the ashes of my shame?!

Really it's to be expected though when shoehorning support for a different game into an FFXV tool in the span of just two weeks. I've generally just started using "the game" instead in such messages, but this is one from before Forspoken support was added. May as well quickly tidy that up when the next patch goes out.

**Comment by Kizari** [comment]
Fixed in 1.5.13.
