### ISSUE TITLE
[Bug]: Patreon Authentification Failed

### ISSUE THREAD

**Issue by Lennn888** [Kizari/Flagrum#155]
### Operating System

Windows 10 64-Bit

### Game Version

Latest Steam Release

### Version

1.5.12

### Description of the bug

Hello,

Happens on launch. Timing makes me think it has to do with:

https://www.patreondevelopers.com/t/status-400-https-www-patreon-com-api-oauth2-v2-identity/8836/2

something something User-Agent header something something... In that case latest comment at the moment in thread above provides the solution.

Hopefully it is just that, but let me know if not and I can provide more information, logs or whatever.

### Steps to reproduce the bug

1. Start Flagrum

Congratulations, warning is now displayed on your screen!

### Code of Conduct

- [X] I confirm that I have ensured this bug hasn't already been reported in another issue on this repository.
- [X] I confirm that this bug report is pertaining to Flagrum, not an individual mod, the game itself, or an issue with my system or files.
- [X] I confirm that I am using a legitimate copy of the game.
- [X] I confirm that I installed Flagrum with a clean installation of the game, and have not used any tools other than Flagrum to mod my game files.
- [X] If my issue relates to the game itself crashing or exhibiting unexpected behaviour, I confirm that I have tried running a clean unmodded installation of the game to see if this resolves my issue before filing a bug report.

**Comment by Kizari** [comment]
Thanks for the heads up. Patreon doesn't actually let me authenticate my own account with Flagrum since I'm not technically a member of my own campaign, so it's not something I'm made aware of when they break the auth like this. Not currently posting a `User-Agent` header with the requests to Patreon so that'll be the first thing to try.

**Comment by Kizari** [comment]
As you noted, Patreon temporarily rolled back this change to afford users time to update their integrations. However, this has been sorted anyway to keep ahead of things. If the problem returns once they push this update out once again, please reopen the issue.
