### ISSUE TITLE
Moved Game Profile Location Breaks Flagrum

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#159]
### Operating System

Windows 10 64-Bit

### Game Version

Latest Steam Release

### Version

1.5.14

### Description of the bug

Switching flagrum profiles to one where the file path has change or isnt accessible causes flagrum to crash.

Rebooting / restarting flagrum will still cause the crash.

this issue can easily be worked around by ignoring the crash pop up, going to settings, changing the path then restarting.

after restarting i suggest ensuring the oath is still correct, closing flagrum correctly and restarting it an additional tike to make sure the profile is updated  

### Steps to reproduce the bug

Create a profile (on an external if possible)
Switch profiles back to your other games profile
Change the external’s drive letter, or just move the folder i assume of the one you just created
Restart flagrum

### Crash logs

I can provide if needed, but the log just says shirts missing or bitlocker encrypted 

### Additional context

This has an easy work around so can be ignored, but potentially can corrupt your flagrum installation, and has a few tines for myself. But relatively speaking, this should be pretty rare and has a simple work around.

in a way this is operational, but i do think having a way to re-input a profile path to prevent crashing should be possible as ignoring the error lets me do that. 

### Code of Conduct

- [X] I confirm that I have ensured this bug hasn't already been reported in another issue on this repository.
- [X] I confirm that this bug report is pertaining to Flagrum, not an individual mod, the game itself, or an issue with my system or files.
- [X] I confirm that I am using a legitimate copy of the game.
- [X] I confirm that I installed Flagrum with a clean installation of the game, and have not used any tools other than Flagrum to mod my game files.
- [X] If my issue relates to the game itself crashing or exhibiting unexpected behaviour, I confirm that I have tried running a clean unmodded installation of the game to see if this resolves my issue before filing a bug report.

**Comment by Kizari** [comment]
Isn't this a duplicate of #153? Or am I missing something?

**Comment by Rinual** [comment]
damn, though this was bundled into the complicated story issue

**Comment by Kizari** [comment]
No worries, appreciate it anyway. Just wanted to make sure I wasn't dismissing a similar but separate issue as a duplicate.
