### ISSUE TITLE
Mods not working

### ISSUE THREAD

**Issue by AuritaDusty** [Kizari/Flagrum#161]
### Operating System

Windows 11 64-Bit

### Game Version

Latest Steam Release

### Version

v1.5.14

### Description of the bug

I've used Flagrum before for FFXV and it works fine, then I stopped playing due to being busy with university and when I want to get back to FFXV, all the mods no longer work. The paths are all correct. I tried to redownload Flagrum and all the mods but still no luck. The regenerating file index also did nothing. I'm very confused on why it doesn't work at all.

### Steps to reproduce the bug

none

### Additional context

I've looked to previous closed issues to see if there's anyone who got the same problem and I found one but unfortunately there was no solution for that since the OP stop replying about the issue

### Code of Conduct

- [X] I confirm that I have ensured this bug hasn't already been reported in another issue on this repository.
- [X] I confirm that this bug report is pertaining to Flagrum, not an individual mod, the game itself, or an issue with my system or files.
- [X] I confirm that I am using a legitimate copy of the game.
- [X] I confirm that I installed Flagrum with a clean installation of the game, and have not used any tools other than Flagrum to mod my game files.
- [X] If my issue relates to the game itself crashing or exhibiting unexpected behaviour, I confirm that I have tried running a clean unmodded installation of the game to see if this resolves my issue before filing a bug report.

**Comment by Rinual** [comment]
Just to confirm:

1) You are using the steam release, not a different version of the game
2) you are not using the Avatara Mod on nexus
3) You have tried the force reset button on flagrum's settings. 

Anything that changes the game's exe will break flagrum, if you are unsure, validate your game files with steam integrity check for the game.

**Comment by AuritaDusty** [comment]
1. Yes it's the Steam release
2. Nope, I don't have that mod at all
3. Yes, I've already tried that step and also have verify the game files through Steam

**Comment by Rinual** [comment]
While mods are applied, check two things:
1) next to your ffxv exe, is their a hid.dll file and hook.fhc ?
2) from there go into the data folder, is a folder called patch being generated there?

**Comment by AuritaDusty** [comment]
1. both files are there
2. yes, there is a patch folder in datas

**Comment by Rinual** [comment]
Someone in our discord had the same issue today:

> What ended up working was, deleting the contents of my FFXV steam folder, and then verifying files and having steam repair what was missing. Uninstalling and reinstalling seemed to keep track of whatever change was corrupted

**Comment by AuritaDusty** [comment]
ahhh it works noww, tysm for the helpp :)
