### ISSUE TITLE
Asset Explorer 3D model preview viewport sits outside the window on some devices

### ISSUE THREAD

**Issue by Kizari** [Kizari/Flagrum#17]
A user has reported that on their device, the 3D viewport sits outside the Flagrum window.

It still otherwise works as expected, and can be worked around by switching to "File System" view and back, or switching to the "Mod Manager" tab and back between previewing each model. This is inconvenient, but it means for the affected user(s) it is still workable for now.

The nature of the issue is that the viewport always hugs the left-hand side of the screen, but is otherwise as expected. The vertical offset, width, and height are all correct. It is currently unknown why this occurs or what is different about the affected device(s) that causes this.

**Comment by Kizari** [comment]
The three devices so far that this has occurred on happened to be running Windows 10 64-Bit Professional (same version as the developer) with different language settings to the developer and the users that have not had this issue. Perhaps this is somehow related to locale? (i.e. number formatting or such)

**Comment by Rinual** [comment]
User with US / English Locale has reported experiencing this issue.

**Comment by Kizari** [comment]
It's not totally clear what was causing this, but essentially it seems like the 3D viewer position was inverted on some computers as though it was trying to use a RTL layout or use a right-handed tablet mode or something. However, this shouldn't have been occurring as at least some of the devices affected were not touch-screen enabled nor using a RTL language. Regardless, this has been fixed in Flagrum 1.3.5 by using a custom window layout placement for the 3D viewer to prevent this default behaviour from doing strange things.
