### ISSUE TITLE
[Request]: Edit of game files BINS

### ISSUE THREAD

**Issue by Xehanort88** [Kizari/Flagrum#171]
### Feature Request

Is .bins edit planned or has this project been abandoned? 

### Proposed Value

Allows for gameplay modifications in terms of proper ability edit.

### Code of Conduct

- [X] I confirm that I have ensured this feature hasn't already been suggested in another issue.
- [X] I confirm that I believe this suggestion would benefit many users of Flagrum, not just myself.

**Comment by Rinual** [comment]
this is not a planned feature for a number of reasons. The format is not fully known, and what is known has not revealed an obvious way that tooling could be made for it, and even after that, it would require very custom file parsing to allow for multiple edits to the same bin file to allow for multiple people to edit the same file. All of which would be immense projects and all development in FFXV is currently on a permanent hiatus.
