### ISSUE TITLE
Model replacement presets don't work correctly when created from scratch

### ISSUE THREAD

**Issue by Kizari** [Kizari/Flagrum#24]
This is an issue from quite a long time ago that was forgotten about, so I don't recall many details.

Basically, if a model replacement preset (for Workshop) is created using the "Create New Preset" button, the mod will not build quite right.

### Workaround

Simply clone an existing preset and set the paths you want in the cloned preset to avoid this bug until it is fixed.

**Comment by Rinual** [comment]
Workaround apparently no longer needed
