### ISSUE TITLE
ReadMe Wrap around and Re-Scaling

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#31]
Readme has a very odd wrap around declaration, by the point at which it successfully does, and if the user continues typing a bit more after it successfully wraps around, the left frame of the window becomes distorted. 

![image](https://user-images.githubusercontent.com/108095289/204162074-35fe7855-4f18-4c54-9781-8a2afeae63f3.png)

Developer should consider constraining the size of the left, right, or both frames

**Comment by Kizari** [comment]
This is fixed in Flagrum 1.3.1.
