### ISSUE TITLE
Create Preset UI Asset Explorer Glitch

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#32]
Issue using the up a folder button while creating custom presets. 

To Replicate:

1. Mod Workshop tab inside flagrum
2. New Mod -> Model Replacement -> Create Preset
3. Navigate down any file path, then use the up arrow to navigate back a folder
4. go back into any folder
5. die a little inside

![image](https://user-images.githubusercontent.com/108095289/204169949-b44404b1-4fc5-4ff1-a918-7f1f9079891a.png)

**Comment by Kizari** [comment]
I get a slightly different result when following these steps, but probably the same thing in essence. When navigating back up, it seems only the folder from the path I originally went down is present, while all other folders in the same directory are missing.

Not sure on the exact cause off the top of my head, but probably won't be difficult to discern when I look into it.

**Comment by Kizari** [comment]
This is fixed in Flagrum 1.3.3.
