### ISSUE TITLE
Environment Importer crashes on 1.2.4 Plugin 

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#37]
Importing group_galdin.fed that is confirmed fine in 1.2.3 results in the following error. 

![image](https://user-images.githubusercontent.com/108095289/209233858-c1da6cb7-37dd-4ea2-a179-b0e65a399761.png)

Possibly related, Blender 3.4 may have issues with any version of the plugin currently, resulting in a similar error. 

![image](https://user-images.githubusercontent.com/108095289/209233968-dde96760-9573-4479-9dd2-cd76de0e57dd.png)

To users with similar issues:
Reverting Flagrum Plugin back to 1.2.3 via the revert key within the addon settings within blender, or uninstalling there and reinstalling the previous version of the plugin from [here](https://github.com/Kizari/Flagrum-Blender/releases). 

Blender 3.4 is currently untested for many features of flagrum, we recommend using 3.0 or 3.3 versions of blender that are known to be fully compatible. You can install a 2nd version of blender without uninstalling as well if you have the space.

**Comment by Kizari** [comment]
First issue is fixed in Flagrum Blender 1.2.5.
Second issue could not be reproduced. If this continues to be a problem for anyone, please open a new issue with as much detail as possible so it can be looked into again.
