### ISSUE TITLE
Add Forspoken Support

### ISSUE THREAD

**Issue by Kizari** [Kizari/Flagrum#40]
Since Forspoken runs on Luminous and is packed into earc files like XV, it is largely compatible with Flagrum with some small adjustments.

Forspoken should be supported as much as possible so that new tooling won't need to be built from scratch for it, especially considering the quality of Flagrum as a modding suite.

I have already started by making the Asset Explorer work with Forspoken on the forspoken branch. Currently working towards enough support to comfortably merge this into the main branch to join FFXV on the release builds.

**Comment by Kizari** [comment]
Because so much work is still needed for FFXV and I am the only active developer working on XV, I won't be able to focus fully on Forspoken. As such, if anyone is coming here for Forspoken, it would be greatly appreciated if you could submit any Forspoken functionality as a pull request. I would be more than happy to accommodate.

I am also happy to discuss and assist with Forspoken features as required, either here or in our Discord server (link on the README).

**Comment by Kizari** [comment]
That would be awesome. Let me know if there's anything I can do to accommodate, since this was all setup originally with only FFXV in mind.

**Comment by orangpelupa** [comment]
how to grab the setup for the forspoken branch?

**Comment by Kizari** [comment]
Forspoken is now supported as of Flagrum 1.4+, so closing this issue.
