### ISSUE TITLE
Error when exporting Blender scene to FMD

### ISSUE THREAD

**Issue by Jey-G** [Kizari/Flagrum#42]
Hi, i'm pretty new to modding in general. I wanted to do a model swap mod, but when i try to export with the flagrum addon, i get this error and i dont understand what it means..

any help would be appreciated

I am using blender 3.0 with the latest flagrum addon

![Untitled](https://user-images.githubusercontent.com/126422269/221437624-e83d9813-2e73-489a-96cb-f4d4df4a8f61.png)

**Comment by Kizari** [comment]
This occurs when you haven't assigned Flagrum materials to every mesh in the scene. You can either delete the meshes that aren't going in-game if any, or assign materials to those that are missing them.

There's a full start-to-finish guide here if you want to make sure you're not missing any steps:
https://github.com/Kizari/Flagrum/wiki/Creating-An-Outfit-Mod

Or a more comprehensive guide about Flagrum materials here:
https://github.com/Kizari/Flagrum/wiki/Materials-Tutorial

**Comment by Jey-G** [comment]
oh i hadnt noticed there was a section on materials in that tutorial. Sorry for the inconvenience. thanks
