### ISSUE TITLE
GFXBIN code fails for props and models with more than one mesh object

### ISSUE THREAD

**Issue by Kizari** [Kizari/Flagrum#6]
**Note for Readers**
This does not affect any of Flagrum's functionality, this is a reference to using the code to write models programmatically.

1. Writing a prop model produces a broken result. This can be reproduced with the following code:
```
var gmdl = File.ReadAllBytes(@"path\to\some\prop\model.gmdl.gfxbin");
var gpubin = File.ReadAllBytes(@"path\to\some\prop\model.gpubin");
var reader = new ModelReader(gmdl, gpubin);
var model = reader.Read();
var writer = new ModelWriter(model);
(gmdl, gpubin) = writer.Write();
File.WriteAllBytes(@"path\to\some\output.gmdl.gfxbin", gmdl);
File.WriteAllBytes(@"path\to\some\output.gpubin", gpubin);
```
The output can then be imported into Blender to see the problem.

2. Writing a model with more than one MeshObject also causes problems. This appears to be due to a boolean at the start of the MeshObject that if memory serves is not present on subsequent mesh objects. This will need to be looked into to clarify the details properly.

**Comment by Rinual** [comment]
Results are not entirely consistent for models. For example code has been used successfully to remove the crystal from /sm05/, but unable to remove a jacket from /uw04_100/. The edited model does load correctly back into Blender, however the game crashes when the gfxbin and gpubin are replaced.

**Comment by Kizari** [comment]
I suspect the format may not have been reversed entirely correctly since almost all testing was done on outfit models with only one MeshObject. It is possible there are multiple issues in the format and that could be why the issues appear to vary and appear across different types of models.

Because these models all appear to import correctly (i.e. the reader is fine), this may be an issue with the writer only, or otherwise a very tiny nuance like the boolean described in the original issue.

**Note for Developer**
It would be worth observing the structure of several different problem models to ensure the issue is resolved across the board.
Consider checking at least the following:
* At least one prop model (as far as we're aware, most of these break)
* uw04_100 (as mentioned by Rinual above)

**Comment by Kizari** [comment]
Closing this as the gmdl.gfxbin writer has been rewritten.
