### ISSUE TITLE
Automaterials: NROs and Combining Normal Maps

### ISSUE THREAD

**Issue by katekittaly** [Kizari/Flagrum#65]
The attached blend file contains an example of an nro texture for the automaterial importer (the tree). 

It also contains the node for combining micronormals with a main normal map (the NPC shirt). Since not all normal map combining will involve _n textures, like the _noto in this example, your normalise node has to remain outside the combine normal maps node, with the normal map node itself removed. However, sometimes we will require the normalise node with the normal map node included. I was unable to think of a way to universalize this process without having two normalise nodes. 
[New Nodes.zip](https://github.com/Kizari/Flagrum/files/11279384/New.Nodes.zip)

**Comment by Kizari** [comment]
Great suggestions, and brilliant shader you've attached. I've added these to the automaterials in Flagrum-Blender 1.4.0. Thank you!
