### ISSUE TITLE
Unable to Change Existing Profile Names

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#68]
![image](https://user-images.githubusercontent.com/108095289/234357850-6df6583f-1abd-4d36-9b1d-753da3e7343b.png)
using the Edit Profile button to change the name results in [flagrum crashing](https://github.com/Kizari/Flagrum/files/11325307/editing.profile.name.log)

**Comment by Kizari** [comment]
I wasn't able to reproduce by simply opening this page and renaming a profile, but when I attempted to rename it a second time, I got the same exception.

Seems that the Entity Framework change tracker just needs to be cleared after a profile operation is committed or something.

**Comment by Kizari** [comment]
This is fixed in Flagrum 1.4.9.
