### ISSUE TITLE
Incorrect Scaling on n1s, fac on n1s

### ISSUE THREAD

**Issue by katekittaly** [Kizari/Flagrum#74]
In importing nh04_010 (Lunafreya in the Oracle dress), her micronormals do not import with the correct UV scale and power. 

A related but separate issue, the masks for the rocks in Ravatogh were connected to the UV scaled node when they shouldn't be. Below is a URI to a single rock with that issue, but there were many.

data://environment/duscae/props/du_te_Wrava01/models/du_te_ravatocliffDA.gmdl
du_te_ravatocliffda_mm_$h.tga is the texture. It is also automatically set to srgb, when all mm textures should be non-color.

Add a fac to the combine normals node and default the second set to 1:
![image](https://github.com/Kizari/Flagrum/assets/84484382/77d1e13b-7613-4ec2-85bc-b2a44f069921)

For a model with an n1 and a mask, ve00_000, mat ve00_000_basic_02_mat. The correct mask is mm1.

**Comment by katekittaly** [comment]
Update report from 5/22 release:
(see above for relevant URIs)
1. The mm textures are still importing as srgb on the rock, the second mm texture for the car seats is as well.
2. One of the mask UV scales is correct for the rock, but the second is still tiling. I looked up the material data://environment/duscae/props/du_te_wrava01/materials/du_te_ravatocliffda_mt.gmtl, and it says it should be 1. This isn't a huge deal since it's the same mask, and one would normally get deleted anyway, but it may cause issues down the road.
3. Micronormals with no mask plugged in look great! (Lunafreya's dress)
4. The UV scale for the micronormal on ve_00_000 did not import correctly. Should be 200, 200. Is it Square being inconsistent with naming conventions again like with Lunafreya? I wasn't expecting the mask to import already plugged in, that was a nice surprise!

**Comment by katekittaly** [comment]
Issue with notos on newest Blender add on. 
Example on um_04_201. Material slot um04_201_UhCloth_01_mat.
![image](https://github.com/Kizari/Flagrum/assets/84484382/2d6b81c9-6795-4ce5-a71b-1afb4229296b)
noto should only combine r and g and leave b white. It does not require an ensure blue normals node. Messes up normals.

**Comment by Kizari** [comment]
Closing this as most of these have now been addressed. Please open a new issue for the combine normals mask problem as it's becoming tricky to track everything going on in this thread.
