### ISSUE TITLE
New Setup for NRTs

### ISSUE THREAD

**Issue by katekittaly** [Kizari/Flagrum#75]
Disconnect NRT from the transmission slot and delete the invert node. Plug alpha channel of NRT texture into the subsurface slot. Plug the diffuse into subsurface color.  Change the subsurface radius to .001, .001, .001. 

For th textures, set to non color and plug into subsurface. Diffuse into ss color. .001 radius for all three channels.

URI for NRTs: data://environment/leide/props/le_pl_GQplant1/models/le_pl_GQplant1_seaA.gmdl
![image](https://github.com/Kizari/Flagrum/assets/84484382/134eab4d-d27b-4fe5-994a-0046502bba66)

URI for th: data://environment/leide/props/le_pr_GQobj2/models/le_pr_GQobj2_objG.gmdl
![image](https://github.com/Kizari/Flagrum/assets/84484382/80688ee5-154e-4360-9802-bd2b5c7f7785)

**Comment by Kizari** [comment]
This has now been added. Thank you for your submission!
