### ISSUE TITLE
Forspoken Indexing Error

### ISSUE THREAD

**Issue by Greedo75** [Kizari/Flagrum#79]
Trying to load mods related to Forspoken and am getting an "Already indexed" error. I do not know how to resolve it. Please help. I cannot load any mods until this is resolved.
<img width="296" alt="Forspoken Index Error" src="https://github.com/Kizari/Flagrum/assets/139670163/732e8b80-7833-48f4-ba54-7da7498549a3">

**Comment by Kizari** [comment]
Hey there, this should only happen if one of your profiles already has the Forspoken exe set as the game path. Please check your other profiles and if it is set on any of them, clear it or change those to point to a different exe—then try again.

**Comment by Greedo75** [comment]
Thank you for your response. Although I understand what the error message is stating, I do not know how to "check other profiles" as there are no menu options to do so.

**Comment by Kizari** [comment]
On the left menu, select the "Settings" tab. There is a dropdown on the top-right with your profiles in it.

![image](https://github.com/Kizari/Flagrum/assets/25322543/dd5161b2-4adf-4128-b6d6-9ff0bd2bd18a)

I know you're trying to get things working for Forspoken, but make sure you check the Final Fantasy XV profile as well just in case it ended up in there somehow.

**Comment by Greedo75** [comment]
I do not have that left panel. None of those options are available. Perhaps I have a different version?
<img width="644" alt="Flagrum SS" src="https://github.com/Kizari/Flagrum/assets/139670163/06ac5240-a675-4c4a-8db4-76c2ebaded28">

**Comment by Kizari** [comment]
![image](https://github.com/Kizari/Flagrum/assets/25322543/74761b3a-3885-4a74-816b-649f3db0232e)

**Comment by Greedo75** [comment]
Figured it out. I was running v1.1. I downloaded v1.4. The menus appear on the left. The mods were installed. The changes are present in the game. Thank you for your assistance. 

Is there a mod that will force PS4 buttons to show up? I have a PS controller, but X-Box button prompts are visible in the game.

**Comment by Kizari** [comment]
Glad you got it working! All Forspoken mods are available [here](https://modworkshop.net/g/forspoken), so if such a mod exists, you'll find it there: Best of luck!
