### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by LavenderAndChamomile** [Kizari/Flagrum#84]
I have installed Flagrum and installed the mod to change Noctis' Chocobo, then verified the Steam game files. I started the game, went to the Chocobo farm and went to customise Noctis' Chocobo and only the standard colours were there.

Am I doing anything wrong?

Many thanks.

**Comment by Rinual** [comment]
Do not set the color via chocobo girl, if the mod is fully enabled and you see the mod on this screen
![image](https://github.com/Kizari/Flagrum/assets/108095289/e8452bec-f0a3-4b2b-bee5-a111f656f109)

then just use the whistle as normal and they will work.

**Comment by LavenderAndChamomile** [comment]
> 

I just want to rent a Chocobo and now it works?! Very odd, as it didn't work even before I didn't change the colours. Anyway, thank you for your help! <3
