### ISSUE TITLE
Environment Importer Issues (8/28 Release)

### ISSUE THREAD

**Issue by katekittaly** [Kizari/Flagrum#88]
1. notos are not connected correctly. They can't take the ensure blue normals node but need a combine red, green, with blue set to 1. 

2. Combine normals is missing the mask option of the old version (from 7/13 release)

3.  The UV scales are not importing for many things anymore (maybe everything, haven't run across anything correctly scaled yet). Neither for main mats or micronormals. The floor of the Leville is an example. data://environment/altissia/props/al_in_hotel03/models/al_in_hotel03.gmdl

4. Many mesh pieces are missing. I think they are not instancing. data://environment/altissia/props/al_pr_fount02/models/al_pr_fount02_typ05a.gmdl only gave me one when there should be 6 in the file. There are also booths missing with floating merchandise.

**Comment by Kizari** [comment]
This is now resolved. If the issue persists, please reopen the issue with relevant comments.

**Comment by katekittaly** [comment]
•	nrt and th maps: set to random walk (fixed radius) (my fault for not including that last time--sorry!)
•	UV scaling still not working for main or detail textures: data://environment/altissia/props/al_in_hotel03/models/al_in_hotel03.gmdl
ux05_100: ux05_100_UhSkin_00_mat

**Comment by Kizari** [comment]
My bad, forgot to merge some material reader fixes over from another branch. UV scale issues should be fixed now. NRT and TH materials are now automatically set to fixed radius as well as suggested since it's a better fit for the majority of cases in XV environments.
