### ISSUE TITLE
Crash when disabling and installing conflicting mods quickly

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#90]
I had 4 mods targeting the same file, i would install, disable when prompted, install, disable repeat when prompteds and then manually disabled the last one. resulting in 
[crash.txt](https://github.com/Kizari/Flagrum/files/12644811/crash.txt)

work around = Dont do that, just be chill. that is all

**Comment by Kizari** [comment]
This is such a non-issue that most people will never encounter, and even if they do it has such a simple workaround. As such, have marked this as low priority. Probably won't ever address it myself (if it's even still a problem in the current build), but will leave it around in case anyone picks up development of the Forspoken side of things.

**Comment by Rinual** [comment]
have not been able to replicate this in the most recent 1.5.9 anyways, so closing it for now
