### ISSUE TITLE
Automats: _r

### ISSUE THREAD

**Issue by katekittaly** [Kizari/Flagrum#92]
Set textures with _r to non color and plug into roughness.

data://environment/altissia/props/al_ar_resid01/models/al_ar_resid01_rooma.gmdl
mat name: ac_in_marble_piller01
ac_marble07_r_$h.tga

**Comment by Kizari** [comment]
Oh goodness, that's a difficult one. I'm not sure I'm up to the challenge!

**Comment by Kizari** [comment]
Turns out these were already setup for M, R, and S for Forspoken, but it's called "RoughnessTexture0" there while it's "Roughness0Texture" in XV. I just added the XV variants to the texture slot detection so it should now handle all three if they ever appear isolated in XV.
