### ISSUE TITLE
The new version of Flagrum, version 1.5.0, is unable to recognize the DEBUG version of FFXV.

### ISSUE THREAD

**Issue by bailimoyin** [Kizari/Flagrum#93]
The new version of Flagrum cannot recognize the FFXV with the debug version. After updating to version 1.5.0, Flagrum no longer recognizes the legitimate version of FFXV that I am using with the debug patch. When using the debug patch, the version of FFXV is lowered to 1138403. In version 1.4.11, I was able to use Flagrum's mods normally. However, after the update, none of the mods are working. I tried removing the debug patch and verifying the integrity of FFXV, and Flagrum started working again. But for certain reasons, I have to use the DEBUG mode to modify some aspects. Is it still possible to apply Flagrum to the DEBUG version of FFXV as before?

**Comment by Rinual** [comment]
It isn't possible. Flagrum only supports the latest version of the game and relies on elements only in the release build.
