### ISSUE TITLE
New mod cards for Comrades Binmods cause game crashes

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#98]
**Describe the bug**
Creating a new mod for Comrades, the booting ffxv.exe will crash at the nodes to load binmods on the title ebex. 

**To Reproduce**
1. Go to Flagrum
2. Click on New Mod
3. Scroll down to Comrades
4. See error (Not yet, thats later)

Then finish making the mod for comrades and selecting the .fmd

**Expected behavior**
The game should not crash. 

**Crash logs**
ffxv.exe does not have crashlogs, please make a hook for that ty. 

**Screenshots**
![image](https://github.com/Kizari/Flagrum/assets/108095289/83ddd776-17ac-4bee-a121-b85d08e89f7a)

**Additional context**
Reverting to branch 1.4.12 and making the mod there with the same .fmd allows the game to boot fine. And using that newly made card back in 1.5.2 allows the game to boot up again. But making another new mod after using the same fmd causes it to crash. 

To fix this error: It is recomended users refrain from making mods for or playing comrades.

**Comment by Kizari** [comment]
Possibly related to #97 since this also caused issues for binmods in the major refactor in 1.5. Due to the above, I'm not willing to put in the effort to test it was fixed with everything on my plate already, but if someone else can confirm that would be great.
