### ISSUE TITLE
Flagrum Legacy Mod - Installation Issues

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#99]
**Describe the bug**
Flagrum crashes when installing legacy mod

**To Reproduce**
1. Go to [modworkshop](https://modworkshop.net/mod/40364)
2. install with flagrum via `Install Mod` button

**Expected behavior**
It should install and be enabled. Currently it crashes, then is found under disabled. 

**Crash logs**
Flagrum produces two crash logs for this. 

[2023-10-15_07-41-31-6859_crash_1834916711.txt](https://github.com/Kizari/Flagrum/files/12910925/2023-10-15_07-41-31-6859_crash_1834916711.txt)
[2023-10-15_07-41-31-6904_crash_2063196466.txt](https://github.com/Kizari/Flagrum/files/12910926/2023-10-15_07-41-31-6904_crash_2063196466.txt)

**Additional context**
legacy mods suck, users should ask the author to update it to fmod instead of needing flagrum to maintain compatibility

**Comment by Kizari** [comment]
> Go to modworkshop

![927201401203998780](https://github.com/Kizari/Flagrum/assets/25322543/b2091815-3b2a-4908-9b4c-d65ebe7ad211)

**Comment by Kizari** [comment]
Seems this was specifically an error with metadata version 1 of the Flagrum zip mods. I misplaced a bracket when refactoring the mod installers to make them easier to maintain, which was causing it to add an archive to the build list for every single file inside that archive. Oops. Fixed in 1.5.3.
